### ISSUE TITLE
Error when Hex Edit App, [Errno 13] Permission denied

### ISSUE THREAD

**Issue by SupDos** [CrafterPika/ppsideloader_py#3]
When typing the App Exec Name and pressing Hex Edit App, I get the following error:

![screenshot](https://user-images.githubusercontent.com/6813986/97058567-78bb1d00-158e-11eb-97ff-705320112dcc.png)

Have tried both 1.4 and 1.5, both error out in this step. Is this an issue with the .ipa, or am I doing something wrong? Thanks!

**Comment by CrafterPika** [comment]
umm yea you extracted the ipa wrong. the content off YouTube.app not the folder itself.

**Comment by SupDos** [comment]
I'm sure I did that correctly, since I put app.zip and tweak.zip in the root folder, press Extract Files and let it do it's thing. This is the YouTube folder, showing that it is the contents of YouTube.app, not the folder itself 
![image](https://user-images.githubusercontent.com/6813986/97369288-f17ee980-18ac-11eb-9195-991d7f2ce644.png)

**Comment by SupDos** [comment]
Aha, got it! Yeah, looks like I did it wrong, I moved the contents of that YouTube folder back into ppsideloader.app, and it worked! Thanks very much

**Comment by CrafterPika** [comment]
np
